version: '3.8'

services:
    redis:
        image: redis:7-alpine
        ports:
          - "6379:6379"
        volumes:
          - redis_data:/data
        networks:
            - cleverhire

    database:
        image: postgis/postgis:17-3.4
        environment:
            - DB_NAME= ${DB_NAME}
            - DB_PASSWORD= ${DB_PASSWORD}
            - DB_USER= ${DB_USER}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5433:5433"
        healthcheck:
            test: ["CMD-SHELL", "pg_is_ready -U cleverhire"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - cleverhire

    rabbitmq:
        image: rabbitmq:3.12-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        healthcheck:
          test: rabbitmq-diagnostics -q ping
          interval: 30s
          timeout: 10s
          retries: 5
        networks:
            - cleverhire
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        command: >
            sh -c "python manage.py migrate &&
                  python manage.py collectstatic --noinput &&
                  gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 4"
        volumes:
            - .:/app
            - static_volume:/app/staticfiles
            - media_volume:/app/media
        ports:
            - "8000:8000"
        environment:
            - DJANGO_ENV=${DJANGO_ENV}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
            - EMAIL_HOST_USER=${EMAIL_HOST_USER}
            - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
            - SECRET_KEY=${SECRET_KEY}
            - DEBUG=${DEBUG}
            - REDIS_URL=${REDIS_URL}
            - CELERY_BROKER_URL=${CELERY_BROKER_URL}
            - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
            - FRONTEND_URL=${FRONTEND_URL}
        depends_on:
            database:
              condition: service_healthy
            redis:
              condition: service_started
        networks:
            - cleverhire

    celery_worker:
        build:
          context: .
          dockerfile: Dockerfile
        command: celery -A config worker -l info
        volumes:
          - .:/app
        env_file:
          - .env
        depends_on:
          - backend
          - rabbitmq
          - redis
        networks:
            - cleverhire

    celery_beat: 
        build:
          context: .
          dockerfile: Dockerfile
        command: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
        volumes:
          - .:/app
        env_file:
          - .env
        depends_on:
          - backend
          - rabbitmq
          - redis
        networks:
            - cleverhire
    flower:
        build:
          context: .
          dockerfile: Dockerfile
        command: celery -A config flower --port=5555
        ports:
          - "5555:5555"
        env_file:
          - .env
        depends_on:
          - celery_worker
          - rabbitmq
    

networks:
    cleverhire:
        driver: bridge

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  static_volume:
  media_volume: