version: '3.8'

services:
    redis:
        image: redis:7-alpine
        volumes:
            - redis_data:/data
        restart: unless-stopped
        networks:
            - cleverhire

    database:
        image: ostgis/postgis:16-3.4
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped
        networks:
            - cleverhire


    rabbitmq:
        image: rabbitmq:3.12-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 30s
            timeout: 10s
            retries: 5
        restart: unless-stopped
        networks:
            - cleverhire

    backend:
        image: saisrinu135/cleverhire-backend:latest
        command: >
            sh -c "python manage.py migrate &&
                  python manage.py collectstatic --noinput &&
                  gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3"
        volumes:
            - static_volume:/app/staticfiles
            - media_volume:/app/media
        expose:
            - "8000"
        env_file:
            - .env
        depends_on:
            database:
                condition: service_healthy
            redis:
                condition: service_started
        restart: unless-stopped
        networks:
            - cleverhire

    celery_worker:
        build:
            context: .
            dockerfile: Dockerfile
        command: celery -A config worker -l info
        env_file:
            - .env
        depends_on:
            - backend
            - rabbitmq
            - redis
        restart: unless-stopped
        networks:
            - cleverhire

    celery_beat: 
        build:
            context: .
            dockerfile: Dockerfile
        command: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
        env_file:
            - .env
        depends_on:
            - backend
            - rabbitmq
            - redis
        restart: unless-stopped
        networks:
            - cleverhire

    flower:
        image: mher/flower:2.0
        ports:
            - "5556:5555"
        environment:
            - CELERY_BROKER_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672//
            - FLOWER_PORT=5555
        depends_on:
            rabbitmq:
                condition: service_healthy
        restart: unless-stopped
        networks:
            - cleverhire
    nginx:
        image: nginx:alpine
        ports:
            - "9000:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - static_volume:/app/staticfiles
            - media_volume:/app/media
        depends_on:
            - backend
        restart: unless-stopped
        networks:
            - cleverhire

networks:
    cleverhire:
        driver: bridge

volumes:
    postgres_data:
    redis_data:
    rabbitmq_data:
    static_volume:
    media_volume:
