services:
    redis:
        image: redis:7-alpine
        container_name: cleverhire_redis
        restart: always
        volumes:
          - redis_data:/data
        networks:
            - cleverhire

    database:
        image: imresamu/postgis:16-3.5-alpine
        container_name: cleverhire_db
        restart: always
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - cleverhire

    rabbitmq:
        image: rabbitmq:3.12-management-alpine
        container_name: cleverhire_rabitmq
        restart: always
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        healthcheck:
          test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
          interval: 10s
          timeout: 5s
          retries: 5
        networks:
            - cleverhire

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: cleverhire_backend
        restart: always
        command:
            - sh
            - -c
            - |
                python manage.py migrate &&
                python manage.py collectstatic --noinput &&
                gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 4
        volumes:
            - ./staticfiles:/app/staticfiles
            - ./media:/app/media
        env_file:
            - .env
        depends_on:
            database:
              condition: service_healthy
            redis:
              condition: service_started
        networks:
            - cleverhire

    celery_worker:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: cleverhire_celery
        restart: always
        command: celery -A config worker -l info
        env_file:
          - .env
        depends_on:
          - backend
          - rabbitmq
          - redis
        networks:
            - cleverhire

    celery_beat: 
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: cleverhire_beat
        restart: always
        command: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
        env_file:
          - .env
        depends_on:
          - backend
          - rabbitmq
          - redis
        networks:
            - cleverhire

    flower:
        image: mher/flower:2.0
        container_name: cleverhire_flower
        restart: always
        environment:
            - CELERY_BROKER_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672//
            - FLOWER_PORT=5555
            - FLOWER_URL_PREFIX=flower
        depends_on:
            rabbitmq:
                condition: service_healthy
        networks:
            - cleverhire
    
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: cleverhire_frontend
        restart: always
        command: sh -c "npm run build && npm start"
        environment:
            - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
            - NEXT_PUBLIC_API_VERSION=v1
        depends_on:
            - backend
        networks:
            - cleverhire

networks:
    cleverhire:
        driver: bridge

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data: