# Generated by Django 5.2.9 on 2026-01-04 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterModelOptions(
            name='savedjob',
            options={'verbose_name': 'Saved Job', 'verbose_name_plural': 'Saved Jobs'},
        ),
        migrations.AlterModelOptions(
            name='savedsearch',
            options={'verbose_name': 'Saved Search', 'verbose_name_plural': 'Saved Searches'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelTable(
            name='job',
            table='jobs',
        ),
        migrations.AlterModelTable(
            name='savedjob',
            table='saved_jobs',
        ),
        migrations.AlterModelTable(
            name='savedsearch',
            table='saved_searches',
        ),
        migrations.AlterModelTable(
            name='skill',
            table='skills',
        ),
    ]
