# Generated by Django 5.2.9 on 2026-01-10 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='branch',
        ),
    ]
