# Generated by Django 5.2.9 on 2026-01-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0002_alter_companyprofile_managers_companyprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='companies', to='core.location'),
        ),
    ]
