# Generated by Django 5.2.9 on 2026-01-10 14:36

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_companyprofile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
