# Generated by Django 5.2.9 on 2026-03-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_profile_completeness_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-start_date'], 'verbose_name': 'Education', 'verbose_name_plural': 'Educations'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date'], 'verbose_name': 'Experience', 'verbose_name_plural': 'Experiences'},
        ),
        migrations.AlterModelTable(
            name='education',
            table='educations',
        ),
    ]
