# Generated by Django 5.2.9 on 2026-01-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_companyprofile_founded_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_token',
            field=models.UUIDField(blank=True, default=None, editable=False, null=True),
        ),
    ]
