# Generated by Django 5.2.9 on 2026-01-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_companyprofile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_token',
            field=models.CharField(blank=True, default=None, editable=False, null=True, unique=True),
        ),
    ]
