# Generated by Django 5.2.9 on 2026-01-22 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_completeness',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='visibility_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
