# Generated by Django 5.2.9 on 2026-01-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_options_alter_application_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchscore',
            options={'verbose_name': 'Match Score', 'verbose_name_plural': 'Match Scores'},
        ),
        migrations.AlterModelTable(
            name='matchscore',
            table='match_scores',
        ),
    ]
